Creación solicitud autorizacion de giro
udistrital/central_cuentas_crud pull request #17
Opened 2022-03-03 03:51 UTC by diagutierrezro

udistrital/central_cuentas_cliente#141

2022-03-03 04:40 UTC, AlexFBP requested changes

2022-03-03 04:40 UTC, AlexFBP commented on .env
> +export CENTRAL_CUENTAS_MONGO_COLLECTION=orden_pago
Si es posible, intentar eliminar, no depender de `CENTRAL_CUENTAS_MONGO_COLLECTION`... Dada la jerarquía de Mongo, debería bastar no mas con `CENTRAL_CUENTAS_MONGO_DB_NAME`. Confirmarlo con DBAs

El equivalente Postgres de las colecciones mongo serían las tablas...

2022-03-03 04:40 UTC, AlexFBP commented on .gitignore
> +!.vscode/extensions.json
De paso ajustar lo siguiente:
```diff
-.vscode/*
-!.vscode/settings.json
-!.vscode/tasks.json
-!.vscode/launch.json
-!.vscode/extensions.json
+.vscode
```

2022-03-03 04:40 UTC, AlexFBP commented on docker-compose.yml
>              - CENTRAL_CUENTAS_MONGO_COLLECTION=${CENTRAL_CUENTAS_MONGO_COLLECTION}
Ver comentario en `.env` respecto a `CENTRAL_CUENTAS_MONGO_COLLECTION`

2022-03-03 04:40 UTC, AlexFBP commented on src/autorizacion-giro/dto/autorizacion-giro.dto.ts
> +}
(En general) Dejar vacía la última linea de cualquier archivo de texto seguido por Git
```suggestion
}

```

2022-03-03 04:40 UTC, AlexFBP commented on src/autorizacion-giro/dto/documento.dto.ts
> +}
```suggestion
}

```

2022-03-03 04:40 UTC, AlexFBP commented on src/autorizacion-giro/schemas/autorizacion-giro.schema.ts
> +export const AutorizacionGiroSchema = SchemaFactory.createForClass(AutorizacionGiro);
```suggestion
export const AutorizacionGiroSchema = SchemaFactory.createForClass(AutorizacionGiro);

```

2022-03-03 04:40 UTC, AlexFBP commented on src/autorizacion-giro/schemas/documento.schema.ts
> +export const DocumentoSchema = SchemaFactory.createForClass(Documento);
```suggestion
export const DocumentoSchema = SchemaFactory.createForClass(Documento);

```

2022-03-03 04:51 UTC, diagutierrezro commented on .env
> +export CENTRAL_CUENTAS_MONGO_COLLECTION=orden_pago
Se elimina `CENTRAL_CUENTAS_MONGO_COLLECTION` de las variables de entorno para conectar a db

2022-03-12 20:01 UTC, AlexFBP requested changes
En general, bien
Un ajuste menor y quedaría

2022-03-12 20:01 UTC, AlexFBP commented on entrypoint.sh
>  exec node dist/main
(En general) Dejar vacía la última línea, sin espacios ni nada, de cualquier archivo de texto
```suggestion
exec node dist/main

```

2022-03-15 00:01 UTC, AlexFBP approved these changes

2022-03-15 00:06 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/central_cuentas_crud/23)

2022-03-15 00:06 UTC, merged