Creación de Ordenes de pago
udistrital/central_cuentas_crud pull request #21
Opened 2022-04-18 07:09 UTC by diagutierrezro

udistrital/central_cuentas_cliente#145

2022-04-18 17:37 UTC, AlexFBP requested changes
En general, bien. Revisar si faltan algunos campos por [lineamiento de DBs](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md#columnas)

2022-04-18 17:37 UTC, AlexFBP commented on src/orden-pago/dto/imputacion-presupuestal.dto.ts
> -    readonly Activo: boolean;
Por qué se eliminan estos campos? Tener en cuenta el [lineamiento para dbs](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md#columnas), aplica también para mongo...

2022-04-18 17:37 UTC, AlexFBP commented on src/orden-pago/dto/movimiento-contable.dto.ts
> -    readonly Activo: boolean;
Estos campos por qué se eliminaron? Tener en cuenta el [lineamiento para dbs](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md#columnas)

2022-04-18 17:37 UTC, AlexFBP commented on src/orden-pago/dto/impuestos-retenciones.dto.ts
> +export class ImpuestosRetencionesDto {
A no ser que corresponda a una coleccion de parametros, faltarían los campos de lineamiento: Fechas de creación/modificación y activo

2022-04-18 17:37 UTC, AlexFBP commented on src/orden-pago/schemas/impuestos-retenciones.schema.ts
> +export class ImpuestosRetenciones extends Document {
A no ser que esta clase sea para una entidad paramétrica, faltarían los campos por lineamiento (fechas y activo)

2022-04-18 17:37 UTC, AlexFBP commented on src/orden-pago/schemas/imputacion-presupuestal.schema.ts
> -    Activo: boolean
Por qué se eliminaron estos campos? A no ser que sea una entidad asociada a una coleccion/"tabla" paramétrica, el [lineamiento para dbs](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md#columnas) sigue aplicando a las colecciones de Mongo

2022-04-18 17:37 UTC, AlexFBP commented on src/orden-pago/schemas/movimiento-contable.schema.ts
> -    Activo: boolean
Por qué se eliminaron estos campos? Tener en cuenta el [lineamiento para columnas de dbs](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md#columnas)

2022-04-18 17:39 UTC, AlexFBP commented
En caso que alguna de las entidades esté asociada a parámetros, revisar la [sección asociada en los lineamientos para DBs](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md#tablas-tipo-cat%C3%A1logo-o-param%C3%A9tricas)

2022-04-19 00:51 UTC, diagutierrezro commented on src/orden-pago/dto/impuestos-retenciones.dto.ts
> +export class ImpuestosRetencionesDto {
Los impuestos y retenciones se usan para agregarlo dentro de un arreglo en la orden de pago general, la fecha de creacion, modificación y activo se crean en la orden de pago como tal

2022-04-19 00:51 UTC, diagutierrezro commented on src/orden-pago/dto/imputacion-presupuestal.dto.ts
> -    readonly Activo: boolean;
Esos campos se van a manejar en la orden de pago, esta estructura de datos se usa para guardar datos dentro del mismo registro de la OP

2022-04-19 00:51 UTC, diagutierrezro commented on src/orden-pago/dto/movimiento-contable.dto.ts
> -    readonly Activo: boolean;
Movimiento contable se usa como un arreglo dentro de la op, no son necesarios estos campos acá

2022-04-19 05:11 UTC, AlexFBP approved these changes

2022-04-19 05:11 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/central_cuentas_crud/38)

2022-04-19 05:12 UTC, merged